FROM python:3.11-slim

WORKDIR /app
COPY requirements.api.txt requirements.txt params.yaml ./
RUN pip install --no-cache-dir -r requirements.api.txt
COPY app ./app
COPY src ./src
COPY docs ./docs
COPY models ./models
COPY reports ./reports
COPY data ./data

EXPOSE 8000
CMD ["uvicorn", "app.gateway:app", "--host", "0.0.0.0", "--port", "8000"]
